### ISSUE TITLE
Selenium Chrome Driver

### ISSUE THREAD

**Issue by kodermax** [ryfeus/lambda-packs#1]
Hello,
How can i use chromedriver on aws lambda?

**Comment by ryfeus** [comment]
@kodermax didn't look at it yet. My search shows me that we may need to compile gtk+ for that one - https://itsallabtamil.blogspot.com/2013/02/setting-up-chrome-firefox-ec2-selenium-java.html .

**Comment by MichaelMartinez** [comment]
I am using the chrome binaries from [serverless-chrome](https://github.com/adieuadieu/serverless-chrome) and/or [lambdium](https://github.com/smithclay/lambdium) to work on Lambda with zero success. I am having PATH errors and exited 127 errors. Getting Chrome and Selenium to work was actually more difficult than it ought to be with Docker as well.... lots of little gotchas with versions and rapid development.

**Comment by ryfeus** [comment]
@MichaelMartinez I believe the closest thing is https://github.com/graphcool/chromeless . I'm not sure whether I can replicate it using python so for now it is the only option.
