### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by duttasantanuGH** [ryfeus/lambda-packs#10]
Have not done any changes. But on testing in lambda getting the following error message.

Getting the error message : Unable to import module 'service': No module named keras.models

Please help to resolve it.

**Comment by ryfeus** [comment]
@duttasantanuGH are you using following pack https://github.com/ryfeus/lambda-packs/blob/master/Keras_tensorflow/Pack.zip ?

It works out of the box so I guess I need to see exact code you are trying to deploy in terms of libraries.

Also I would suggest to move to Tensorflow 1.4 (https://github.com/ryfeus/lambda-packs/blob/master/Tensorflow/Pack.zip) as it already contains Keras. The import can be done in the following way:
```
from tensorflow.python.keras.models import load_model
```
