### ISSUE TITLE
[Tensorflow] An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError

### ISSUE THREAD

**Issue by Beomi** [ryfeus/lambda-packs#12]
# Exception Logs

```
An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
File "/var/task/index.py", line 125, in handler
downloadFromS3(strBucket,strKey,strFile)
File "/var/task/index.py", line 19, in downloadFromS3
s3_client.download_file(strBucket, strKey, strFile)
File "/var/runtime/boto3/s3/inject.py", line 130, in download_file
extra_args=ExtraArgs, callback=Callback)
File "/var/runtime/boto3/s3/transfer.py", line 299, in download_file
future.result()
File "/var/runtime/s3transfer/futures.py", line 73, in result
return self._coordinator.result()
File "/var/runtime/s3transfer/futures.py", line 233, in result
raise self._exception
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

# Situation

Used `serverless` to start this..

```
serverless install -u https://github.com/ryfeus/lambda-packs/tree/master/tensorflow/source -n tensorflow
cd tensorflow
serverless deploy
serverless invoke --function main --log
```

However it makes Exception above, that I don't have permission for access to your Bucket, `ryfeuslambda`.

```python
strBucket = 'ryfeuslambda'
strKey = 'tensorflow/imagenet/imagenet_synset_to_human_label_map.txt'
strFile = '/tmp/imagenet/imagenet_synset_to_human_label_map.txt'
downloadFromS3(strBucket,strKey,strFile)  
```

is this the situation you intended?

**Comment by ryfeus** [comment]
@Beomi thank you for pointing that out. It wasn't intended. I changed permissions for the bucket recently and forgot that I referenced it in this code.

**Comment by jrios6** [comment]
Followed your instructions on https://serverless.com/blog/using-tensorflow-serverless-framework-deep-learning-image-recognition/ and still received the same error "An error occurred (403) when calling the HeadObject operation: Forbidden".

**Comment by nonflet** [comment]
same problem :(

**Comment by jrios6** [comment]
@nonflet The error is exists because the application doesn't have read access to ryfeuslambda bucket. 
I resolved it by uploading my own copy of imagenet_synset_to_human_label_map.txt, imagenet_2012_challenge_label_map_proto.pbtxt and classify_image_graph_def.pb to my S3 Bucket, and modified the code to download from there instead.

**Comment by ryfeus** [comment]
@jrios6 @nonflet Thank you for feedback. I believe that ryfeuslambda is a public bucket. Still it may happen that you need to add permissions to read it within serverless configuration. The alternative as @jrios6 mentioned is to host model on your bucket. @jrios6 thank you for suggestion.

Let me know if there are any issues.
