### ISSUE TITLE
Trying to change the model

### ISSUE THREAD

**Issue by jda91** [ryfeus/lambda-packs#16]
I got permission errors trying to access your bucket, so I decided to unpack your pack, change the s3 arguments to my model in my bucket (a retrained inception v3 model), and zip that. When I upload it, I get a no module named index error, am I doing something wrong? Also I have no idea how to write AWS Lambda functions yet, how would I go about writing the lambda test function? Lets say I want to upload an image from my mobile application using HTTPS  to the function and have it classify that? Is that possible?

**Comment by ryfeus** [comment]
@jda91 here is good articles about starting with AWS Lambda + Tensorflow for project similar to yours:

https://medium.freecodecamp.org/making-the-web-more-accessible-with-ai-84598eebabdb

"module named index" comes from name of the handler in Lambda - it should be <name of the file>.<name of the function>. Let me know if I need to elaborate.
