### ISSUE TITLE
refresh pandas package

### ISSUE THREAD

**Issue by yiga2** [ryfeus/lambda-packs#17]
Any chance you can refresh the pandas_numpy with the latest 0.22 ?

**Comment by ryfeus** [comment]
@yiga2 I don't have time this week but I will try to do it during next week.

**Comment by yiga2** [comment]
Much appreciated !

**Comment by yiga2** [comment]
@ryfeus as I need 0.22, can you point on how to create these packages ? Am a bit novice but don't mind trying. Thanks !

**Comment by ryfeus** [comment]
@yiga2 updated pandas pack to 0.22 https://github.com/ryfeus/lambda-packs/commit/7250f1b4dd7d8109d4d248c12d9bdcd667926598
Also added bash script https://github.com/ryfeus/lambda-packs/blob/master/Pandas_numpy/buildPack.sh in case you need to refresh it.
