### ISSUE TITLE
Max memory usage - Internal server error

### ISSUE THREAD

**Issue by iNDicat0r** [ryfeus/lambda-packs#2]
Hi,
Basically i am using the inception model to extract features for a single image:

```
pool3 = sess.graph.get_tensor_by_name('incept/pool_3:0')
pool3_features = sess.run(pool3, {'incept/DecodeJpeg/contents:0': data})
```

However 1/2 of the time the function gives an error (Internal server error) and i can see in cloudWatch that its because of max memory usage. I have increased the memory limit to 1536MB and can't go further.

Any idea ?

**Comment by ryfeus** [comment]
@iNDicat0r I've looked into it and I think that it may be connected with image size so I think there are two main options - resize image or crop image. I know that it's not a perfect solution but it may be close to the task you want to solve.
