### ISSUE TITLE
Magpie package : Multi label text classification 

### ISSUE THREAD

**Issue by Sach97** [ryfeus/lambda-packs#20]
Hi, great work ! You inspired me to build my own package for a project that you can find on my [repo](https://github.com/Sach97/serverless-multilabel-text-classification). Unfortunately I'm facing an issue.

I have this [error](https://github.com/Sach97/serverless-multilabel-text-classification/issues/1). Have you already seen this type of error before ?

**Comment by ryfeus** [comment]
@Sach97 answered in the thread.
