### ISSUE TITLE
Lamda Packs for Tensorflow 1.6 based on Python 3

### ISSUE THREAD

**Issue by SumanthReddyKaliki** [ryfeus/lambda-packs#21]
Hi, I'm trying to create a lamda pack for tensorflow 1.6 based on Python 3.
However I am not able to compress the pack to be less than 50 MB. 

Can you please share your taught's on how to do that.

**Comment by ryfeus** [comment]
@SumanthReddyKaliki feel free to check https://github.com/ryfeus/lambda-packs/tree/master/Keras_tensorflow_nightly .

50 MB is not a hard limit - you can read more here https://hackernoon.com/exploring-the-aws-lambda-deployment-limits-9a8384b0bec3
