### ISSUE TITLE
[Request] Lambda Pack for Selenium + Python + Chrome headless

### ISSUE THREAD

**Issue by ankitsam** [ryfeus/lambda-packs#23]
Can you please create Lambda Pack for Selenium + Python + Chrome/Firefox headless.
Since http://phantomjs.org is now suspended the project.

**Comment by ryfeus** [comment]
@ankitsam sorry for the delay. Here is the link to the pack https://github.com/ryfeus/lambda-packs/tree/master/Selenium_Chromium. I will add documentation later. Currently the pack is made for python3.6 .

**Comment by ankitsam** [comment]
@ryfeus Wow, Thank you so much  :smiley: :smiley: :smiley:
