### ISSUE TITLE
Getting error on uploading Pack.zip for Tesseract 

### ISSUE THREAD

**Issue by ankitsam** [ryfeus/lambda-packs#24]
```
START RequestId: c1cf2730-90e1-11e8-8015-797f4abdd12c Version: $LATEST
Unable to import module 'main': No module named httplib2

END RequestId: c1cf2730-90e1-11e8-8015-797f4abdd12c
REPORT RequestId: c1cf2730-90e1-11e8-8015-797f4abdd12c	Duration: 0.31 ms	Billed Duration: 100 ms 	Memory Size: 512 MB	Max Memory Used: 20 MB	
```

**Comment by ryfeus** [comment]
@ankitsam could you please share more about runtime and memory of your lambda. It supposed to be python 2.7 . Result will look something like this:

```
START RequestId: e79c0d73-9113-11e8-bbf4-abdd7d9e82c0 Version: $LATEST
LD_LIBRARY_PATH=/var/task/lib TESSDATA_PREFIX=/var/task ./tesseract /tmp/imgres.png /tmp/result
Start
Finish
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Error in pixGenHalftoneMask: pix too small: w = 307, h = 63

Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Sed semper accumsan turpis,
sit amet volutpat Iorem mattis non. Proin


END RequestId: e79c0d73-9113-11e8-bbf4-abdd7d9e82c0
REPORT RequestId: e79c0d73-9113-11e8-bbf4-abdd7d9e82c0	Duration: 1211.76 ms	Billed Duration: 1300 ms 	Memory Size: 1536 MB	Max Memory Used: 99 MB
```

**Comment by ankitsam** [comment]
Runtime - python 2.7
Memory - 512 MB
![2018-08-01 14_30_18-lambda management console](https://user-images.githubusercontent.com/343092/43511985-7f085278-9597-11e8-8f79-0feecee4bf81.png)
![2018-08-01 14_30_23-lambda management console](https://user-images.githubusercontent.com/343092/43511986-7f6ae532-9597-11e8-9059-d449a7900597.png)

**Comment by ryfeus** [comment]
@ankitsam Handler is supposed to be "service.handler" or you can change service.py file to main.py file.

**Comment by ankitsam** [comment]
Great. That worked. Thank you.

**Comment by ankitsam** [comment]
But is service.handler set somewhere? because I had created copy of `service.py` as `main.py` and set the `handler = main.handle`

**Comment by ryfeus** [comment]
@ankitsam It is also set here https://github.com/ryfeus/lambda-packs/blob/master/Tesseract/source/serverless.yml but it shouldn't matter since you are using apex.
