### ISSUE TITLE
add opencv/PIL to Keras_tensorflow pack

### ISSUE THREAD

**Issue by amanmeetgarg** [ryfeus/lambda-packs#28]
Hi @ryfeus , Thanks for sharing your great work with the world. 

I have a keras model trained on TF backend. I need to serve this through a lambda function. My model takes image as input and uses openCV at training time.

In my testing the keras_tensorflow pack does not have openCV. Is there a way I can include openCV into the Pack ? or what could be a possible alternative ?

What changes do I need to make in this case ? Or what steps do I need to take to add opencv/pil into the keras pack ?

Apologies if the question is naive, I am new to the lambda world.

Thanks
Aman

**Comment by ryfeus** [comment]
@amanmeetgarg Thanks for suggestion. I've published nightly Tensorflow OpenCV pack https://github.com/ryfeus/lambda-packs/tree/master/Tensorflow_OpenCV_Nightly . No documentation yet, I will add it later. Some things to keep in mind:

- it is nightly package meaning it's more than 50MB and should be uploaded via S3
- Tensorflow 1.2 so it is not the most recent once
- made for python3.6

Let me know if you have any questions.
