### ISSUE TITLE
Numpy, Pandas and TF ?

### ISSUE THREAD

**Issue by MonkeyChap** [ryfeus/lambda-packs#29]
Would it be feasible to do all three, or is that just too big for Lambda ?

**Comment by ryfeus** [comment]
@MonkeyChap Thanks for suggestion. I've published nightly Tensorflow Pandas Numpy pack https://github.com/ryfeus/lambda-packs/tree/master/Tensorflow_Pandas_Numpy . No documentation yet, I will add it later. Some things to keep in mind:

- it is nightly package meaning it's more than 50MB and should be uploaded via S3
- Tensorflow 1.2 so it is not the most recent once
- made for python3.6

Let me know if you have any questions.
