### ISSUE TITLE
Issue running Selenium example after modifying and zipping source files

### ISSUE THREAD

**Issue by adrianfr1010** [ryfeus/lambda-packs#3]
Hello,
I was able to successfully run Pack.zip from the Selenium_PhantomJS dir in Lambda. I then zipped everything in the source dir (without modifying the files at all) and tried to run that zip, but I got the following exception:

`Message: 'phantomjs' executable may have wrong permissions. 
: WebDriverException
Traceback (most recent call last):
  File "/var/task/service.py", line 26, in lambda_handler
    browser = webdriver.PhantomJS(service_log_path=os.path.devnull, executable_path="/var/task/phantomjs", service_args=['--ignore-ssl-errors=true'], desired_capabilities=dcap)
  File "/var/task/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/var/task/selenium/webdriver/common/service.py", line 76, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'phantomjs' executable may have wrong permissions. `

Any advice?

Thanks!

**Comment by ryfeus** [comment]
@adrianfr1010 from https://stackoverflow.com/questions/40446084/webdriverexception-message-phantomjs-executable-may-have-wrong-permissions

```
chmod u + x phantomjs
```

It seems that when I've uploaded files to github, it changed permissions on phantomjs executable. So alternatively you unzip pack and modify it.

**Comment by g4spow** [comment]
Had the same issue here. I can download the pack.zip and upload to Lamda. Works perfect.

As soon as I unzip locally on Windows 10, edit service.py then save. I then zip, upload to S3 and run the Lambda which then fails withthe error below and a load of other stuff
'phantomjs' executable may have wrong permissions. 

Tried many variants and solutions from the web with no success

**Comment by ryfeus** [comment]
@g4spow I don't have windows so I can't reproduce the error. It seems that the only way is to gather pack on Unix VM and check permissions.

**Comment by fredliporace** [comment]
You may also try to test it with an editor and ZIP utilities in cygwin. I've been using this configuration without any problem - did not try with selenium pack specifically though.
