### ISSUE TITLE
lightgbm with tensorflow

### ISSUE THREAD

**Issue by tarlen5** [ryfeus/lambda-packs#31]
I have a similar question as https://github.com/ryfeus/lambda-packs/issues/29 and that is the question of whether lightgbm and tensorflow can be installed in a single lambda or is this just too large for lambda to handle?

**Comment by ryfeus** [comment]
@tarlen5 Thanks for suggestion. I've published nightly Tensorflow LightGBM pack https://github.com/ryfeus/lambda-packs/tree/master/Tensorflow_LightGBM_Scipy_nightly . No documentation yet, I will add it later. Some things to keep in mind:

- it is nightly package meaning it's more than 50MB and should be uploaded via S3
- it doesn't have sklearn, so LightGBM doesn't support sklearn API
- Tensorflow 1.2, Scipy 1.0.0 so they are not the most recent once
- made for python3.6

Let me know if you have any questions.
