### ISSUE TITLE
TensorFlow Serving?

### ISSUE THREAD

**Issue by sammefford** [ryfeus/lambda-packs#32]
Any way you could add support for Tensorflow Serving client API's?  When I follow the [official instructions](https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html#python-package-dependencies) for packaging, I download 475MB, way over the 256MB limit.

```
$ python -m pip install tensorflow-serving-api --target .
Collecting tensorflow-serving-api
  Downloading https://files.pythonhosted.org/packages/79/69/1e724c0d98f12b12f9ad583a3df7750e14ec5f06069aa4be8d75a2ab9bb8/tensorflow_serving_api-1.12.0-py2.py3-none-any.whl
...
$ du -hs .
475M    .
```

**Comment by ryfeus** [comment]
@sammefford thanks for the question.

What would be the use case for using Tensorflow Serving on AWS Lambda?

When AWS Lambda uses API Gateway as trigger, it doesn't receive incoming requests through ports which is required for Tensorflow Serving. Instead it receives json with request body and Lambda's return is the response for API request.

Regarding decreasing size of the package - there are some ideas here https://github.com/ryfeus/lambda-packs/blob/master/Tensorflow/buildPack_py3.sh including:
- strip .so files
- remove .pyc files
- remove pip, wheel libs
