### ISSUE TITLE
No package python36-devel available.

### ISSUE THREAD

**Issue by MareArts** [ryfeus/lambda-packs#34]
I am following the example that how to build Tensorflow.
When I input below command

docker exec -i -t lambdapackgen /bin/bash /outputs/buildPack_py3.sh

error is:
...
No package python36-devel available.
No package python36-virtualenv available.
No package python36-pip available.
...

...
rm: cannot remove 'pip': No such file or directory
rm: cannot remove 'pip-*': No such file or directory
rm: cannot remove 'wheel': No such file or directory
rm: cannot remove 'wheel-*': No such file or directory
rm: cannot remove 'easy_install.py': No such file or directory
...

I think this sh doesn't install python36 and then it also doesn't install pip...
How can I fix this?

Thank you for advance!!

**Comment by MareArts** [comment]
--use-wheel
this option is also not support on pip..

**Comment by ryfeus** [comment]
@MareArts You can use the following code to install python36 with pip:

```
yum install -y yum-utils
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install -y python36.x86_64
yum install -y python36-devel.x86_64
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python36 get-pip.py
```

Then everything else should work.

**Comment by MareArts** [comment]
@ryfeus 
Thank you very much for your answers.
I have success to build Tensorflow, but I have this issue when I build opencv

Unable to import module 'index_py3': /var/task/cv2/cv2.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned

I use "pip install opencv-python".

Do you have any idea?
Thank you.

**Comment by ryfeus** [comment]
@MareArts it happens when you strip command runs on some .so files. In the case of this pack you need to make sure that strip command doesn't run on cv2.cpython-36m-x86_64-linux-gnu.so

**Comment by Beomi** [comment]
@MareArts 
Currently, AWS lambda uses amazonlinux:1 version.
Since build script on this repo is targeting `amazonlinux:latest`, 
but recently AWS releases `amazonlinux:2` so currently I'm working on to edit it.
