### ISSUE TITLE
Plan to include PyTorch as a lambda pack?

### ISSUE THREAD

**Issue by Con-Mi** [ryfeus/lambda-packs#36]
Interesting work on this.
Any plans to include PyTorch as a lambda package?

**Comment by Beomi** [comment]
#38 Opened PR :)

**Comment by Con-Mi** [comment]
I have tried your script. It builds it successfully and it fits for the 250MB limit.
However I run the following code:

```
import json
import numpy as np
import torch
from torchvision import models


def predict_handler(event, context):
    img = np.random.rand(1, 3, 224, 224)
    input = torch.randn(1, 1000)
    model = models.densenet121()
    out = model(input)
    return {
        "statusCode" : 200,
        "body" : json.dumps("Some Message")
    }   
```


And I get the following error: 

`Unable to import module 'predict': /var/task/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned`

Any ideas?

**Comment by Beomi** [comment]
@Con-Mi 
I've uploaded pack.zip, it's uncompressed version size is 249MB, so it's compatible with AWS Lambda :)

**Comment by Beomi** [comment]
I'll try it and let you know!

**Comment by Con-Mi** [comment]
Ok it seems that the error is coming when I try to import the Pillow package (from PIL import Image).

A couple of approaches I have tried and were unsuccessful: 
1. I tried to use your script to build on AWS AMI if there is a difference but still I get the same error. I will be happy for more input on this. 
2. I tried with the same pack.zip to just import PIL and do some operation and it seems it fails with the same error
3. I tried to install Pillow in your script by adding pip3 install Pillow
All the above give out the same error

I have tried to include a package that includes Pillow only, build on my machine with pip3 install Pillow --target . 
It seems that is working ok.
I run out of ideas?
Do you have an idea why is this error here?

**Comment by Beomi** [comment]
OK, Got it.
That `pillow` package should NOT be stripped - it'll make a break down with ELF error you've seen.
I'll try with unstripped pillow version too.
Give me time to check it :D

**Comment by Con-Mi** [comment]
Ok so I manage to do it using your script. Change the lines that you strip the packages with the following:
    find -name "*.so" -not -path "*/PIL/*" | xargs strip
    find -name "*.so.*" -not -path "*/PIL/*" | xargs strip

Nothing much here, just skipping anything related to the PIL package.

**Comment by Beomi** [comment]
Great! How was the size of pack.zip file then?

**Comment by Con-Mi** [comment]
247 MB Stripped.
73 MB Compressed

The PIL package is very small in general, like 5MB.
It does not affect much

**Comment by ryfeus** [comment]
Thanks a lot for help. I've merged PRs and also updated pack.zip + added example code.

**Comment by Con-Mi** [comment]
@ryfeus Thats great. I guess this issue should be closed.
