### ISSUE TITLE
error with specified lambda handler

### ISSUE THREAD

**Issue by stasov** [ryfeus/lambda-packs#4]
First of all awesome work!
While trying to use the basic, Skimage, Pack.zip package I got the following error:
Handler 'lambda_handler' missing on module 'service': 'module' object has no attribute 'lambda_handler'

The handler should be service.handler, instead of service.lambda_handler.
When changed it the provided Pack.zip works.

I assume that this might be a problem with other packages as well.

**Comment by ryfeus** [comment]
@stasov Thank you. I've updated documentation.
