### ISSUE TITLE
Proposal: Using Git LFS

### ISSUE THREAD

**Issue by Beomi** [ryfeus/lambda-packs#40]
As git tracks all diffs on binary files, the size of this repo is going bigger and bigger exponentially.
It makes hard to contribute / or just cloning this repo for newbies.

How about using git-lfs and track all the `pack.zip` files with it?
It'll make these procedures much faster.

**Comment by ryfeus** [comment]
Thanks for the suggestion. I've updated the repo with tracking of all pack.zip files.
