### ISSUE TITLE
 Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [ryfeus/lambda-packs#53]
Hello,I found a performance issue in the definition of `synthetic_dataset_helper` ,
[tf.data.Dataset.range(num_batches).map](https://github.com/ryfeus/lambda-packs/blob/5ed3d27f3e7f791b9438e70bda1bf1b986657075/Keras_tensorflow_nightly/source2.7/tensorflow/contrib/eager/python/examples/linear_regression/linear_regression.py#L118) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [dataset = tf.data.TextLineDataset(path).skip(1).map](https://github.com/ryfeus/lambda-packs/blob/5ed3d27f3e7f791b9438e70bda1bf1b986657075/Keras_tensorflow_nightly/source2.7/tensorflow/contrib/eager/python/examples/rnn_colorbot/rnn_colorbot.py#L130) 

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by ryfeus** [comment]
Closed based on PR https://github.com/ryfeus/lambda-packs/pull/54
