### ISSUE TITLE
Deploy fail

### ISSUE THREAD

**Issue by BalajiGite** [ryfeus/lambda-packs#57]
Getting python version error while deploying document generator

**Resource handler returned message: "The runtime parameter of python2.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 7767aad4-e194-48a5-af6a-be7f94eed630)" (RequestToken: 58bfcbfd-1a15-8151-0983-aa9907fce71c, HandlerErrorCode: InvalidRequest)**

**Comment by ryfeus** [comment]
Thank you for the comment. Python2.7 runtimes indeed are no longer supported on AWS Lambda. I will make an update to have only newer runtimes in the repo.
