### ISSUE TITLE
Rename handler in service.py for Selenium_PhantomJS

### ISSUE THREAD

**Issue by sanghviharshit** [ryfeus/lambda-packs#7]
The Readme says - 
```
6. Lambda function handler and role
* Handler - service.handler
```

But the [service.py](https://github.com/ryfeus/lambda-packs/blob/master/Selenium_PhantomJS/source/service.py#L18) has `lambda_handler`.

You might want to rename either Readme or the service.py

**Comment by ryfeus** [comment]
@sanghviharshit Thanks. Updated service.py and pack.zip.
