### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by MichaelMartinez** [ryfeus/lambda-packs#8]
Any chance of a massive update to run with Python 3.6? I would be willing to help if you could teach me how you built the python 2 versions.

**Comment by thess24** [comment]
Seconded.  I'm willing to help if you share some of your tips for compressing these.

**Comment by ryfeus** [comment]
@MichaelMartinez @thess24 sorry for late response and I would welcome your help. I am planning to add dockerfile for each package which installs all necessary dependencies and build the pack. Then it can be modified for python 3.

I am planning to start with lxml package.

**Comment by MichaelMartinez** [comment]
Great. I just need to see how you do it once... then we can build all kinds of software, run some tests and perhaps integrate CI for updates.

**Comment by MichaelMartinez** [comment]
@ryfeus Just a little bump. If you add one dockerfile, I can do the rest...

**Comment by ryfeus** [comment]
@MichaelMartinez bump received) I will publish update later today.

**Comment by ryfeus** [comment]
@MichaelMartinez added bash script:
https://github.com/ryfeus/lambda-packs/blob/master/Lxml_requests/buildPack.sh

Here is how to start it:
```
wget https://github.com/ryfeus/lambda-packs/blob/master/Lxml_requests/buildPack.sh
docker pull amazonlinux:latest
docker run -v $(pwd):/outputs --name lambdapackgen -d amazonlinux:latest tail -f /dev/null
docker exec -i -t lambdapackgen /bin/bash /outputs/buildPack.sh
```

For python 3 I believe the process should be similar.

**Comment by MichaelMartinez** [comment]
Awesome. I will dive in and see what is what...

**Comment by ryfeus** [comment]
Solved in https://github.com/ryfeus/lambda-packs/pull/15

**Comment by chirag912** [comment]
Is there any simpler way to use install (keras,tf,opencv) for python 3.6..?
